#ifndef SERVER__H__
#define SERVER__H__

#include "structs.h"

#define DECLARE_CMD(x) \
	int cmd_##x (struct command * cmd, char * payload, char * response);

DECLARE_CMD(ASSIGN)
DECLARE_CMD(STAT)
DECLARE_CMD(SETATTR)
DECLARE_CMD(STATVFS)
DECLARE_CMD(READ)
DECLARE_CMD(WRITE)
DECLARE_CMD(TRUNCATE)
DECLARE_CMD(DELETE)
DECLARE_CMD(RENAME)
DECLARE_CMD(MKDIR)
DECLARE_CMD(REWINDDIR)
DECLARE_CMD(READDIR)

#define MAX_OPENDIRS 5

#endif
